//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueSeaElJuego.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personaje
    {
        public int PerId { get; set; }
        public string UserName { get; set; }
        public Nullable<short> PerVida { get; set; }
        public Nullable<short> PerDanio { get; set; }
        public Nullable<int> PerExpAcu { get; set; }
        public Nullable<short> PerSuerte { get; set; }
        public string PerNom { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
